gem 'rake'
gem 'resque', '1.25.1'
gem 'resque-pool', github: 'PeopleAdmin/resque-pool',
                   branch: 'config_loader'
gem 'qtrix', path: '..'
gem 'stressque', github: 'PeopleAdmin/stressque'
gem 'capistrano'
